services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  frontend:
    build: ./frontend/excelchat
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
